### ISSUE TITLE
I've run example on README.md and nothing happens

### ISSUE THREAD

**Issue by Firkraag** [posit-dev/great-tables#94] opened 2023-12-17 02:48 UTC
## Prework

- [x] Read and agree to the [code of conduct](https://www.contributor-covenant.org/version/2/1/code_of_conduct/) and [contributing guidelines](https://github.com/posit-dev/great_tables/blob/main/.github/CONTRIBUTING.md).
- [x] If there is [already a relevant issue](https://github.com/posit-dev/great_tables/issues), whether open or closed, comment on the existing thread instead of posting a new issue.

## Question

I've run example on README.md and nothing happens. Is the table shown on screen or saved on some file?

**Comment by Firkraag** [comment] 2023-12-17 02:56
My environment is macOS Ventura Version 13.5.2, Python 3.10.8+

**Comment by machow** [comment] 2023-12-17 16:32
What version do you have installed? There's a bug with cols_hide that we fixed, and still need to release.

In jupyter lab etc.. it should show a fully rendered table. Here's the example from the readme with cols_hide commented out:

https://shinylive.io/py/editor/#code=NobwRAdghgtgpmAXGKAHVA6VBPMAaMAYwHsIAXOcpMASxlWICcyACAZwAsaJsM4APVIzhs2AHQgS6DZiwDmwqGQD6ZKACMANiJZQ28shIBmjYjHmKVarSIwATJVBbSmrNqgCsABi8SJAYhYAETgjbjgWMg4ItjVZKAg7Fkokhwp9IyZI6JY0p0YEuTgJWKhmZTSIgF4WMTAAJi8ARi8AWi8ANnaAdjqJFIqlatqG5rbO1qaAFj7JCECAMRpNCkZ2Tx8WAFc2bjkWAAUEh30yYlyh-XU4MgB3OEoWAANS8sqn3UTngfeSja9lDBuDQWDV3N4vMAABTgnzAOqVOoAXRYAD4wXEVJUAJQsABkLBh-3hYERYBRAB4aj8htikX55iwAMKWCJOOw0dyaKDYSIabQsdR6OBJUjZCIvf6A4EfawCvISKESFgqgwYADiABUoXkqrCAUCIDRscrVRhrMpolA7HBGFCyDQyNoqnUAMp4g4sCF1PDsLbqB1OuBVIx1ECvLFDAC+kXOIBpFCjdRNEFVLAwRhgKkIW0YwgghGwUJImi2MAgbCqJOIqEoPpGXDkHHrdU0xFuLaIbbYxXJKbTGazgwoxeIpfLlYRQ3rlWUsWwzrqtzsgMG2GU2DgZWTppVg5UEDL1ztJbLFZdYAAbmOy73fSR6FBCGQqprGFs4P3Vf4MCW2JaaBtUdx3POprQAK2UQhu17FMUzAKM8HAaB4GoYQAEcthoYR4HINhzX4Mh8CIUgKCoZAFC3MhWjlEQEKRIA

**Comment by machow** [comment] 2023-12-17 16:46
Ah, but if you run it in the console or as part as a .py file (e.g. `python myfile.py`) it won't render a formatted table.

(but you can return formatted html with GT.render("html"))

**Comment by Firkraag** [comment] 2023-12-18 02:43
I've installed great-tables by `pip install great-tables`, the version is 0.1.3.

I've copied the example code to a .py file and run it in console

**Comment by rich-iannone** [comment] 2024-06-17 23:53
This is a duplicate of #100, which should be resolved soon. Closing this one.

**Closed by rich-iannone** 2024-06-17 23:53 UTC
Labels: Type: ⁇ Question
